name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: username/repo
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm run build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://docs.jxlss.cn
